version: "2.23.3"
services:
  web:
    image: nginx:latest
    working_dir: /app
    volumes:
    - ./src:/app
    - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
    - 8080:80
  php:
    image: php:fpm
    working_dir: /app
    volumes:
    - ./src:/app
